"""Add was_edited_by_user field

Revision ID: d232b566f6d0
Revises: d0e3a6ebeed2
Create Date: 2025-12-02 12:07:34.637647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd232b566f6d0'
down_revision: Union[str, Sequence[str], None] = 'd0e3a6ebeed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_entries', sa.Column('was_edited_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_entries', 'was_edited_by_user')
    # ### end Alembic commands ###
